### PR TITLE
Correcting typos in file name and a function name

### PR DESCRIPTION
**Pull request by JessWhitney**
One of the functions had a typo in its definition. Updating that so no errors arise when calling upon the function later on.

### CODE REVIEW

**Review by CosmoMatt — APPROVED** [review]
Nice catch!

**Comment by JessWhitney** [comment]
@CosmoMatt If you're happy with the second change too, I'll merge the PR.

**Comment by CosmoMatt** [comment]
@JessWhitney math.log is one approach, could also use np.log which might be more consistent going forward. Otherwise, as far as I can tell, looks fine.

**Comment by JessWhitney** [comment]
> @JessWhitney math.log is one approach, could also use np.log which might be more consistent going forward. Otherwise, as far as I can tell, looks fine.

Can the same be done for math.ceil -> np.ceil ?

**Comment by CosmoMatt** [comment]
Technically yes but perhaps you're right, if we're already using math.ceil at this level maybe just stick with math.log -- in which case this should be fine to merge whenever you like @JessWhitney

**Comment by JessWhitney** [comment]
Alright I'll stick with the math module for now, we can always amend this later on.

**Pull request merged**
